### ISSUE TITLE
CLI filters for paths and browsers

### ISSUE THREAD

**Issue by jzaefferer** [browserstack/browserstack-runner#107]
Using browserstack-runner on a project with a dozen `test_path` entries and a dozen browsers, I find myself editing the config whenever I need to run a subset of those browsers against a subset of paths. I have to remember reverting those changes to avoid accidentally committing them.

An idea to address that: Two extra CLI options to filter both paths and browsers, so the usage could look something like this:

```
browserstack-runner -p menu -b chrome
```

That would match all paths that contain "menu" and all browsers that contain "chrome", based on what's in the configuration.

Would be good to get some input from others, maybe there's a better way to achieve the same thing.

**Comment by dbollinger** [comment]
+1

Would also be useful to specify browser version (i.e. chrome:39) and OS/device.

**Comment by tchakabam** [comment]
I came up with a little tool recently that might be at least helpful in that direction, even if not the same approach:

https://github.com/tchakabam/browserstack-select

It's not exactly what's requested here but can be useful to others still when wanting to deal with the "full range" of possibilities :)

It's not perfect yet, but I know where I want it to go (see wishlist in readme).

**Comment by mohitmun** [comment]
Released in [v0.9.0](https://github.com/browserstack/browserstack-runner/tree/v0.9.0)
