### ISSUE TITLE
how to configure testing proxied files

### ISSUE THREAD

**Issue by patrickkettner** [browserstack/browserstack-runner#110]
I am unable to figure out how to test urls (rather than files) that are accessed through a proxy. BrowserstackLocal is running, and the proxy information is correct, but `test_paths` [fails unless it is a valid path](https://github.com/browserstack/browserstack-runner/blob/438b5d6690993abb92df8095a5e3e48d9dba70f3/lib/config.js#L67-L70). 

What should a browserstack.json file look like in my case?

**Comment by jzaefferer** [comment]
As far as I can tell, the proxy isn't meant for that. This commit should implement what you're looking for: https://github.com/browserstack/browserstack-runner/commit/d4df62f390a3767cbd8fa54f147cb256fcfd1a7b (from the local_server branch on this repo).

See also #70.
