### ISSUE TITLE
Handle client.getWorkers error

### ISSUE THREAD

**Issue by jzaefferer** [browserstack/browserstack-runner#118]
The [client.getWorkers call in bin/cli.js](https://github.com/browserstack/browserstack-runner/blob/1a5bf9099ea60a13eff2deb3be31cf3551516a33/bin/cli.js#L195) can fail ([as seen in this Travis build](https://travis-ci.org/jquery/qunit/builds/62730719#L321)), but the code ignores the error argument and tries to call `_workers.filter()` anyway. ~~I don't know what the underlying problem was - since most tests finished, its probably not a big deal.~~

**Comment by jzaefferer** [comment]
@nakula @9ikhan can you look into this? We have this issue currently on all our builds on the QUnit project: https://travis-ci.org/jquery/qunit/builds

**Comment by nakula** [comment]
will debug this

**Comment by nakula** [comment]
I see there is no handler for error, should we just retry on error?

**Comment by nakula** [comment]
since this a poller, if i just return and do nothing on error, that should work as well?

**Comment by jzaefferer** [comment]
How about logging the error, then returning? That way the polling can continue, but we also get a chance to find the root issue.

**Comment by nakula** [comment]
yep, sure.

On Sat, Jul 18, 2015 at 12:09 AM, Jörn Zaefferer <notifications@github.com>
wrote:

> How about logging the error, then returning? That way the polling can
> continue, but we also get a chance to find the root issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/browserstack/browserstack-runner/issues/118#issuecomment-122369759>
> .
>



-- 
regards
Nakul Aggarwal
www.browserstack.com

**Comment by leobalter** [comment]
With #122 we're already logging the error, now we just need to return closing the pool properly.

**Comment by jzaefferer** [comment]
So as mentioned elsewhere, the problem is coming from the API rate limiting. From a QUnit run: `Error: 403 Forbidden (Rate Limit Exceeded)`. The rate limit seems a bit strange, since our setup uses 19 workers, but then reuses them for the various pages. The API calls "just" check the status of workers, which shouldn't be a big deal.

Maybe you could adjust the rate limit to apply over a longer time period? For example, instead of 10 requests in 60s, allow 100 requests in 600s. Something along that line would allow browserstack-runner to have some peak requests-per-second, while averaging a reasonable number overall.

**Comment by nakula** [comment]
i think that sounds reasonable, let me discuss internally

On Wed, Jul 22, 2015 at 9:11 PM, Jörn Zaefferer <notifications@github.com>
wrote:

> So as mentioned elsewhere, the problem is coming from the API rate
> limiting. From a QUnit run: Error: 403 Forbidden (Rate Limit Exceeded).
> The rate limit seems a bit strange, since our setup uses 19 workers, but
> then reuses them for the various pages. The API calls "just" check the
> status of workers, which shouldn't be a big deal.
>
> Maybe you could adjust the rate limit to apply over a longer time period?
> For example, instead of 10 requests in 60s, allow 100 requests in 600s.
> Something along that line would allow browserstack-runner to have some peak
> requests-per-second, while averaging a reasonable number overall.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/browserstack/browserstack-runner/issues/118#issuecomment-123762610>
> .
>



-- 
regards
Nakul Aggarwal
www.browserstack.com

**Comment by jzaefferer** [comment]
Btw. the `getWorkers()` call has a timeout of two seconds. While that's good for quick feedback, its also responsible for a lot of API calls. Add to that about 19*7 changeUrl calls and we quickly run into the current limit.

**Comment by shirish87** [comment]
API rate limit has been applied over a longer time period, as suggested. This error should no longer occur for most projects.

**Comment by shirish87** [comment]
Closing this for now since this is unlikely to happen with the new rate limit. Please reopen if you face this issue.
