### ISSUE TITLE
Java process never terminates

### ISSUE THREAD

**Issue by bgaillard** [browserstack/browserstack-runner#119]
I, when I execute the `browserstack-runner` tool it seems a Java process is started. 

When the tests end this process is never terminated on my computer (I'm using a Windows 8.1 64bits OS with Java 1.8.0_05).

**Comment by bgaillard** [comment]
After doing more tests I updated the `lib/local.js` as described in the following pull request https://github.com/browserstack/browserstack-runner/pull/101. 

Because the pull request proposes to use the `BrowserStackLocal.exe` executable file it also solves this issue.

**Comment by nakula** [comment]
@bgaillard this has been published, can you check new runner and close this?

**Comment by bgaillard** [comment]
Hi @nakula, I'm coming back from holidays. 

I tested version 0.3.5 today and it works, thanks !
