### ISSUE TITLE
Testing through Testem

### ISSUE THREAD

**Issue by alexlafroscia** [browserstack/browserstack-runner#120]
I'm trying to get BrowserStack working with Testem, but am having a really hard time getting it set up.  I thought that this might be the right package, but apparently not.  What I need is Browserstack connecting to a test server that is _already_ running locally, but this seems to do the running **and** tunneling to Browserstack.  Do you know how I could get that working?

**Comment by nakula** [comment]
@alexlafroscia there is "local_server" branch in our project. Can you try that? That supports local test server

On other note, testem seems to have inbuild BrowserStack support, isn't it?

**Comment by alexlafroscia** [comment]
Oh cool, I'll check out that branch then.  I actually modified this project in my own fork to support a local server, but maybe that branch will do the trick instead.

I don't think that Testem supports BrowserStack out of the box in any way.  In my research the last few days, I haven't found anything about that, and all of their examples of how to get it working actually don't seem to be valid anymore. Testem, for whatever reason, seems to be unable to quit the BrowserStack CLI program, so the tests get run in BrowserStack but after that, it hangs.

**Comment by nakula** [comment]
I think this is the project: https://github.com/browserstack/browserstack-testem-integration

**Comment by alexlafroscia** [comment]
Unfortunately, all that repo shows is how to write the Testem config, and it doesn't work. Trust me, I've tried ;)

**Comment by alexlafroscia** [comment]
I'll close this since I feel like my question was answered, even if I can't actually get Testem and Browserstack working together
