### ISSUE TITLE
Support tape.js

### ISSUE THREAD

**Issue by cutandpastey** [browserstack/browserstack-runner#136]
Are there any plans to support [tape](https://www.npmjs.com/package/tape) at all?

**Comment by omphalos** [comment]
There is a reporter you can use for tape [here](https://github.com/TehShrike/browserstack-tape-reporter).

**Comment by cutandpastey** [comment]
@omphalos Nice one, thanks!

**Comment by andyhu** [comment]
It's better if browserstack can support type natively...
