### ISSUE TITLE
IPhone "Worker inactive for too long"

### ISSUE THREAD

**Issue by omphalos** [browserstack/browserstack-runner#137]
I've [modified](https://github.com/omphalos/browserstack-runner-sample) browserstack-runner-sample using the IPhone configuration in the browserstack-runner README:

    {
      "os": "ios",
      "os_version": "7.0",
      "device": "iPhone 5S"
    }

This is the error output I see:

    [2015-09-05T07:19:33.966Z] [Runner alert] Worker inactive for too long: ios 7.0, iPhone 5S, Worker details:
    {
        "os": "ios",
        "os_version": "7.0",
        "device": "iPhone 5S",
        "url": "http://localhost:8888/sample.html?_worker_key=2f999b3d-1528-478e-954b-315934f293eb&_browser_string=ios%207.0%2C%20iPhone%205S",
        "project": "browserstack-runner-sample",
        "build": "Local run, 2015-09-05T07:14:26.599Z"
    }

**Comment by shirish87** [comment]
Sorry for the late response, @omphalos. 
Would you mind trying again?

**Comment by omphalos** [comment]
@shirish87 working now, thanks!  I'll close this issue.  BTW do you know what the problem was?

**Comment by shirish87** [comment]
I can't be certain, but i'm guessing the worker could have been queued for a time > inactivity timeout (~300s by default).

If you encounter this issue again, the video for the session in your [BrowserStack Automate dashboard](https://www.browserstack.com/automate) should help in debugging what's going on.
