### ISSUE TITLE
Worker fails to open test page

### ISSUE THREAD

**Issue by jzaefferer** [browserstack/browserstack-runner#138]
I'm trying, once more, to use browserstack-runner to run jQuery UI unit tests. This used to work at some point, currently I'm getting stuck very early in the process.

Here's two builds, one trying to run to regular `button` testpage, the other one excluding jshint:

https://www.browserstack.com/automate/builds/ecec41fcf4a998f2a3d8f3e3e950fb30ea4dc245
https://www.browserstack.com/automate/builds/9fc6435f58d3e9610b8bd491eb3fcb309e1a652e

The first one timed out after an Uncaught error, caused by the jshint module failing to load. I have no idea why that might happen, it works fine outside of browserstack runner.

The second one uses the `?nojshint` querystring to skip jshint, which helps, but the worker also never finishes, timing out eventually. Looking at the video, it actually loads the page after a few seconds, the test suite passes, then it sits there for several minutes. Before it loads the actual test page, it briefly shows "undefined" - I have no idea where that comes from. It seems like adding the query string causes the problem, since I can get successful runs when I drop it, and disable jshint tests by commenting some code.

Here's the config I used:
```json
{
	"username": "BROWSERSTACK_USERNAME",
	"key": "BROWSERSTACK_KEY",
	"test_framework": "qunit",
	"test_path": [
		"tests/unit/button/button.html?nojshint"
	],
	"browsers": [
		"chrome_current"
	]
}
```

**Comment by jzaefferer** [comment]
PS: The issue title is a bit misleading; I started with that, then realized that the page actually loads, but fails to report tests finished.

**Comment by jzaefferer** [comment]
Even when removing the jshint tests (without using a query string), there's still timeouts, like this: https://www.browserstack.com/automate/builds/94c5efa9e55b91ec79215214caa378d983f887a1/sessions/108f41774c720a2a95b88cb64bb9266147fe13a8

**Comment by shirish87** [comment]
Thanks for reporting this issue, @jzaefferer.
Fix for this should land soon. I've setup jquery-ui with your BrowserStack config and the fix [here](https://github.com/shirish87/jquery-ui/tree/browserstack). Run `npm run test-browserstack` : )

**Comment by jzaefferer** [comment]
Thanks, tested today, works great.
