### ISSUE TITLE
"Non existent tunnel"

### ISSUE THREAD

**Issue by josantana** [browserstack/browserstack-runner#143]
Hi there!

I'm trying to run `browserstack-runner` on my project, but I'm getting the following error (when running with `--verbose`):

```
Using config: /Users/xxx/browserstack.json
Launching server on port: 8888
Non existent tunnel
Exiting
```

I tried to replicate the configuration found on *browserstack-runner-sample* repo, just to test.

I don't know what to do to fix this. Hope someone help me.

**Comment by shirish87** [comment]
Hi @josantana,
Could you please share more information on how you're running `browserstack-runner` (OS, config, etc.) and your project structure?

Also ensure that `browserstack-runner` has write access to the folder.

**Comment by ausi** [comment]
I had the same problem due to a connectivity issue while downloading `BrowserStackLocal` from <https://s3.amazonaws.com/browserStack/browserstack-local/BrowserStackLocal-darwin-x64>.

Deleting the file *node_modules/browserstack-runner/lib/BrowserStackLocal* fixed the problem for me.

**Comment by happyhj** [comment]
I think another process is using port 8888 already. In my case, it was MAMP(apache).
Killing the process using port 8888 would solve your problem.

**Comment by shirish87** [comment]
@josantana, have the above suggestions helped resolve the issue?
