### ISSUE TITLE
nightwatch framework

### ISSUE THREAD

**Issue by hayesmaker** [browserstack/browserstack-runner#153]
Does this runner work with nightwatchjs? http://nightwatchjs.org/

If so, how?

**Comment by UmangSardesai** [comment]
Hey,

BrowserStack-Runner is used to run your JS tests on BrowserStack. It is built over BrowserStack's  'JS API' - https://github.com/browserstack/api

Nightwatch is built over Selenium and JSON Wire protocol, and is totally different from JS tests that you would run using BrowserStack-Runner. Hence, integrating Nightwatch and BrowserStack-Runner would not be possible.

Let me know if you need further clarification on this.
