### ISSUE TITLE
server.js - getReporterPatch fails to inject script on Windows machine due to \ in path (instead of /) 

### ISSUE THREAD

**Issue by hagaii** [browserstack/browserstack-runner#158]
on windows, path.relative returns a string with \ slashes and not / slashes.
so in the file server.js. line 49 the comparison return false for the test pages and the framework script is not injected to HTML file.

I solved the issue by replacing \ with / in line 48:

`var filePath = path.relative(process.cwd(), filename).replace(/\\/g,'/');`

**Comment by hagaii** [comment]
Hi any news regarding this issue?!?

**Comment by vedharish** [comment]
Hey, 

The relevant line you mentioned is [this](https://github.com/browserstack/browserstack-runner/blob/f5689b8d03bc4695e2f8a536d94b3f7316bd78ca/lib/server.js#L62). As you mentioned, `path.relative` returns path with `\` on windows.  That path is compared with `testFilePaths` defined [here](https://github.com/browserstack/browserstack-runner/blob/f5689b8d03bc4695e2f8a536d94b3f7316bd78ca/lib/server.js#L18). Each path in that array is formatted with `formatPath` function [here](https://github.com/browserstack/browserstack-runner/blob/f5689b8d03bc4695e2f8a536d94b3f7316bd78ca/lib/config.js#L69) which escapes `/` with `\` for windows [here](https://github.com/browserstack/browserstack-runner/blob/f5689b8d03bc4695e2f8a536d94b3f7316bd78ca/lib/config.js#L5-L7). So this should work even on windows.


I tested this on Windows and it works fine. In your `browserstack.json` file, just use the `test_path` value similar to  `test/index.html` even on Windows.

Example `browserstack.json` file -

```
{
    "username": "BROWSERSTACK_USERNAME",
    "key": "BROWSERSTACK_ACCESS_KEY",
    "test_path": "test/index.html",
    "test_framework": "qunit",
    "browsers": [
        {
            "browser": "firefox",
            "browser_version": "latest",
            "os": "OS X",
            "os_version": "Sierra"
        }
    ]
}
```

@hagaii Please check if this solves your issue

**Comment by hagaii** [comment]
@vedharish 
I checked again and found out that it works if I define only 1 test page in "test_path"  but when I have an array with 2 test pages then it fails. 
Hope it gives you a hint on how to solve this.
Better late then never (I opened this ticket in July)

**Comment by vedharish** [comment]
Hey @hagaii 

Can you please check that the latest release fixes your issue?

**Comment by hagaii** [comment]
Hi @vedharish 
Version 0.5.0 does not work at all. The tests results are not being reported back to the client (the machine that runs browserstack-runner).
We switched back to 0.4.4 and it solved the problem
We are using qunit-2.0 framework for our unit tests

**Comment by vedharish** [comment]
Hey @hagaii 

I tested locally and on a windows machine using qunit-2.0.0 and browserstack-runner 5.0.0. 
Here are the steps I followed to test - [gist](https://gist.github.com/vedharish/e7e22353e2b4259b13b5896bd360d2fe)

Can you please check if the above link is working for you or not?
- if it does not work - 
   - Please tell me the browser/os you were testing on
   - Also, the os/node version you are running this test on/from
- if this works for you too -
   - Can you please give me a small script/test so as to reproduce this issue?

**Comment by hagaii** [comment]
Hi


I investigated the problem and it is not related to the issue we discussed.

The problem in the new version is because you now wrap the output of console.log in a JSON

I have a Gulp task that wraps Browserstack-runner and parse its output, because the output changed to JSON format like this {"arguments": ... } then my build fails.

________________________________

**Comment by hagaii** [comment]
Hi @vedharish please see my comment above

**Comment by vedharish** [comment]
@hagaii 
It seems that you are right. The corresponding change was added in this [PR](https://github.com/browserstack/browserstack-runner/pull/165). I had added same changes [here](https://github.com/browserstack/browserstack-runner/pull/165/files#diff-c945a46d13b34fcaff544d966cffcabaR241) and [here](https://github.com/browserstack/browserstack-runner/pull/165/files#diff-c945a46d13b34fcaff544d966cffcabaR278). But it seems I forgot the change [here](https://github.com/browserstack/browserstack-runner/pull/165/files#diff-c945a46d13b34fcaff544d966cffcabaR350).

I will make the change, test it once and create a PR today. Thanks for pointing it out!

**Comment by vedharish** [comment]
@hagaii 
Or you can send me a PR, just do `CircularJSON.parse` and add the block in `try/catch` just as in other lines. I will test/review it.

**Comment by hagaii** [comment]
@vedharish https://github.com/browserstack/browserstack-runner/pull/172

**Comment by mohitmun** [comment]
@hagaii does latest version fix this issue for you?

**Comment by mohitmun** [comment]
Closing, reopen if still an issue.
