### ISSUE TITLE
console.log in tests doesn't work on IE8 and lower

### ISSUE THREAD

**Issue by vedharish** [browserstack/browserstack-runner#164]
`console.log` in tests on IE8 and lower gives the following error -

```
Launching 1 worker(s) for 1 run(s).
[Windows XP, Internet Explorer 8.0] Failed: 1 tests, 0 passed, 1 failed; ran for 16ms
[Windows XP, Internet Explorer 8.0] Error: "Odd Tests: isOdd()" failed, Died on test #1 undefined: Object doesn't support this property or method
[Windows XP, Internet Explorer 8.0] Screenshot: https://s3.amazonaws.com/testautomation/f5d858132a3cb80355b16a6d6b337b7249dcc601/js-screenshot-1469619378.png
```

[Object doesn't support this property or method](https://s3.amazonaws.com/testautomation/f5d858132a3cb80355b16a6d6b337b7249dcc601/js-screenshot-1469619378.png)

Can reproduce this using `browserstack-runner` version >= 0.4.2

**Comment by jzaefferer** [comment]
Probably related to this? https://github.com/browserstack/browserstack-runner/blob/51618fc87a777777a54c71880c866aed334c5315/lib/_patch/browserstack.js#L35-L49 Though it has been in place pretty long.

**Comment by tr4n2uil** [comment]
Yup, getting console logs to users console is nice feature, hence raised this issue so we fix it :)
