### ISSUE TITLE
Unexpected token in JSON causes tests to fail

### ISSUE THREAD

**Issue by TehShrike** [browserstack/browserstack-runner#167]
A reappearance of #99.

`parseBody` throws when passed the string `data=%7B%22arguments%22%3A%5B%22'%20%20%20%20%20%20%5C%5C'Uncaught%20TypeError%3A%20console.error%20is%20not%20a%20function%5C%5C''%22%5D%7D`

Why call `escapeSpecialCharacters` here at all? https://github.com/browserstack/browserstack-runner/blob/master/lib/server.js#L144

It seems like `qs.parse(body).data` returns valid JSON anyway - why transform it with this escaping function?  If I remove the `escapeSpecialCharacters` call, my tests return correctly.

**Comment by jzaefferer** [comment]
The `escapeSpecialCharacters` is now gone - could you test this again?

**Comment by TehShrike** [comment]
I'll try to get to this soon.

**Comment by TehShrike** [comment]
Can't reproduce any more, closing!
