### ISSUE TITLE
TypeError: Cannot read property 'launched' of undefined, on Travis

### ISSUE THREAD

**Issue by reeteshranjan** [browserstack/browserstack-runner#174]
I tried to get `browserstack-runner` work for my repository https://github.com/reeteshranjan/browse.js on Travis. Though running `browserstack-runner` locally on my desktop worked, things are failing on Travis. I have tried few things as explained below; however, the error is the same in all cases.

Please check https://travis-ci.org/reeteshranjan/browse.js/builds/227335152 for a build that failed. You'll see that an error was thrown after 2 browsers report to be passing.

I am interested in `browserstack-runner` for its JSON format report. I wrote a script as per the documentation here https://github.com/browserstack/browserstack-runner#usage-as-a-module, and a build using my own script `bs-runner.js` with code picked from above failed as well. Here is the link: https://travis-ci.org/reeteshranjan/browse.js/builds/227331984.

I had seen on this page https://www.browserstack.com/automate/travisci that `BROWSERSTACK_LOCAL_IDENTIFIER` variable is important, but did not see the code handling it well, so made my own copies of relevant files from `browserstack-runner` code to have enough changes to include this variable for just trying it out. Interestingly, one build passed and it is here: https://travis-ci.org/reeteshranjan/browse.js/builds/227338890. However; this was not a consistent behavior/result and this build failed: https://travis-ci.org/reeteshranjan/browse.js/builds/227340229. And another build that used my changed code and the `bs-runner.js` script failed as well: https://travis-ci.org/reeteshranjan/browse.js/builds/227339395.

**NOTE**: Please check the repository for `.travis.yml.browserstack-runner` file (as of now I have moved to `testem` for getting my builds to pass, so the  `.travis.yml` file is not the right reference).

**Comment by vedharish** [comment]
Closed via #175
