### ISSUE TITLE
Reports with Jasmine 1.3.1 are not in the format specified in README.md

### ISSUE THREAD

**Issue by reeteshranjan** [browserstack/browserstack-runner#177]
The report format specified in the section https://github.com/browserstack/browserstack-runner#usage-as-a-module is seen to be valid with mocha tests; however, with jasmine 1.3.1 the format is very different. A sample is as follows:

```
{
    "browser": "Windows 10, Chrome 58.0",
    "tests": [],
    "suites": {
      "runtime": 50,
      "total": 2,
      "passed": 2,
      "failed": 0,
      "tracebacks": [],
      "url": "/tests/html/tests.html"
    }
}
```
This Travis build https://travis-ci.org/browsejs/browse.js/builds/230661641 can be looked at for seeing reports generated in this format. The test script run in this build is `bs/run.js` in the repository https://github.com/browsejs/browse.js. It's been written as per the instructions in the section https://github.com/browserstack/browserstack-runner#usage-as-a-module, and it just outputs the report obtained through `browserstack-runner` module, and does not perform any formatting or processing of the report.

**Comment by pulkitsharma07** [comment]
closed by https://github.com/browserstack/browserstack-runner/pull/184
