### ISSUE TITLE
Set correct exit status

### ISSUE THREAD

**Issue by apfelbox** [browserstack/browserstack-runner#181]
Hi,

the runner doesn't seem to set a correct exit code if the build failed.

That's why I have the curious case that the log says:

```
[OS X Sierra, Firefox 54.0] Failed: 39 tests, 38 passed, 1 failed, 0 skipped; ran for 266ms
[OS X Sierra, Chrome 59.0] Failed: 39 tests, 38 passed, 1 failed, 0 skipped; ran for 474ms
All tests done, failures: 2.
```

But the exit code is `0` and travis says

```
The command "npm test" exited with 0.
```

and my build is green.
Is there a chance to set the correct status code?

```
browserstack-runner 0.5.1
npm 5.0.3
node 8.1.3
```

**Comment by ivebe** [comment]
Same issue.

**Comment by pulkitsharma07** [comment]
Should be resolved now. Merged https://github.com/browserstack/browserstack-runner/pull/183.

**Comment by apfelbox** [comment]
Seems to work. Thank you!

You now just have to set `"exit_with_fail": true` in your `browserstack.json`. 🎉
