### ISSUE TITLE
Travis doesn't report complete output

### ISSUE THREAD

**Issue by apfelbox** [browserstack/browserstack-runner#182]
Hi,

if I use the runner locally I get a beautiful output:

<details>
<pre>
▲ ./node_modules/.bin/browserstack-runner
Using config: /.../browserstack.json
Launching 2 worker(s) for 2 run(s).
[OS X Sierra, Chrome 59.0] Error: "isSameDay() tests" failed, next day
Expected: false
  Actual: true
  Source:     at Object.<anonymous> (http://localhost:8888/tests/dist/all-tests.js:1:1630)
          at runTest (http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:1443:30)
          at Test.run (http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:1429:6)
          at http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:1621:12
          at Object.advance (http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:1106:26)
          at begin (http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:2802:20)
[OS X Sierra, Chrome 59.0] Error: "isSameDay() tests" failed, next month
Expected: false
  Actual: true
  Source:     at Object.<anonymous> (http://localhost:8888/tests/dist/all-tests.js:1:1710)
          at runTest (http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:1443:30)
          at Test.run (http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:1429:6)
          at http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:1621:12
          at Object.advance (http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:1106:26)
          at begin (http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:2802:20)
[OS X Sierra, Chrome 59.0] Error: "isSameDay() tests" failed, next year
Expected: false
  Actual: true
  Source:     at Object.<anonymous> (http://localhost:8888/tests/dist/all-tests.js:1:1792)
          at runTest (http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:1443:30)
          at Test.run (http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:1429:6)
          at http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:1621:12
          at Object.advance (http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:1106:26)
          at begin (http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:2802:20)
[OS X Sierra, Firefox 54.0] Error: "isSameDay() tests" failed, next day
Expected: false
  Actual: true
  Source: @http://localhost:8888/tests/dist/all-tests.js:1:1628
      runTest@http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:1443:16
      run@http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:1429:6
      runTest/<@http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:1621:7
      advance@http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:1106:6
      begin@http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:2802:4
      scheduleBegin/<@http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:2762:6

[OS X Sierra, Firefox 54.0] Error: "isSameDay() tests" failed, next month
Expected: false
  Actual: true
  Source: @http://localhost:8888/tests/dist/all-tests.js:1:1708
      runTest@http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:1443:16
      run@http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:1429:6
      runTest/<@http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:1621:7
      advance@http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:1106:6
      begin@http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:2802:4
      scheduleBegin/<@http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:2762:6

[OS X Sierra, Firefox 54.0] Error: "isSameDay() tests" failed, next year
Expected: false
  Actual: true
  Source: @http://localhost:8888/tests/dist/all-tests.js:1:1790
      runTest@http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:1443:16
      run@http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:1429:6
      runTest/<@http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:1621:7
      advance@http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:1106:6
      begin@http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:2802:4
      scheduleBegin/<@http://localhost:8888/node_modules/qunitjs/qunit/qunit.js:2762:6

[OS X Sierra, Firefox 54.0] Failed: 39 tests, 38 passed, 1 failed, 0 skipped; ran for 266ms
[OS X Sierra, Chrome 59.0] Failed: 39 tests, 38 passed, 1 failed, 0 skipped; ran for 474ms
All tests done, failures: 2.
</pre>
</details>

In Travis I just get 

```
Using config: /.../browserstack.json
Launching 2 worker(s) for 2 run(s).
All tests done, failures: 2.
```

```
browserstack-runner 0.5.1
npm 5.0.3
node 8.1.3
test_framework: qunit
```

**Comment by apfelbox** [comment]
Additionally, if I look at the travis output, I get:

```
Using config: /home/travis/build/Becklyn/mojave/browserstack.json
Launching 2 worker(s) for 2 run(s).
All tests done, failures: 2.
```

If I look in the browserstack dashboard, I see that both builds succeeded:

![2017-07-07 at 16 31](https://user-images.githubusercontent.com/1032411/27962275-ae81c686-6331-11e7-90a4-0da205569a6a.png)

**Comment by mohitmun** [comment]
@apfelbox Are you still facing this issue with latest version?

**Comment by mohitmun** [comment]
Closing, reopen if still an issue.

**Comment by apfelbox** [comment]
Hi @mohitmun,
sorry for the late reply.

The new version works for us, thank you! 👍
