### ISSUE TITLE
Demo test doesn't work.

### ISSUE THREAD

**Issue by trusktr** [browserstack/browserstack-runner#186]
When I rune the Node.js sample test from the Automate website, I get an error like this:

```
/usr/local/lib/node_modules/selenium-webdriver/lib/promise.js:2634
        throw error;
        ^

WebDriverError: unknown error: Element <input value="I'm Feeling Lucky" aria-label="I'm Feeling Lucky" id="gbqfbb" name="btnI" type="submit"> is not clickable at point (556, 411). Other element would receive the click: <div class="sbqs_c"
```

**Comment by sinstein** [comment]
If I am understanding this correctly, you tried to run the code sample on [the Automate Node page](www.browserstack.com/automate/node) with browserstack-runner. The code sample on the website is a selenium test which uses webdriver to communicate with the browser.

browsertack-runner runs tests based on the JS Testing API ([documentation on BrowserStack](https://www.browserstack.com/javascript-testing-api))

> Automated JavaScript Testing API is a HTTP-based API that can be used to open any URL, in any combination of browser and OS currently available on BrowserStack, to cross browser test JavaScript files. 

browserstack-runner is not designed to run selenium tests, which is what you seem to have tried.

I am closing this. Please re-open if you think I have misunderstood the issue.
