### ISSUE TITLE
Reporting failed tests doesn't seem to work, at all

### ISSUE THREAD

**Issue by TonyBogdanov** [browserstack/browserstack-runner#191]
This would be the weirdest thing if it's true, but this doesn't seem to be reporting failed tests to BrowserStack at all.

I've tried it both using the sample code from https://github.com/browserstack/browserstack-runner-sample (QUnit) and by using my own with Mocha.

I've spent hours debugging it and I can't seem to find where exactly does the code report the state of the tests to BrowserStack, I just can't find it. I see it creates a worker, makes a screenshot & then terminates the worker. But where is the status reported?

---

So, here's the whole deal.
I'm using a freshly configured VPS server just to avoid the possibility of there being something wrong with my setup.

So I'd go (BrowserStack credentials are in the environment of the terminal):

```shell
git clone https://github.com/browserstack/browserstack-runner-sample .
npm i
npm test
```

It executes all tests, they complete successfully and BrowserStack reports them as successful. All's good so far.

Now I go & change `src/odd.js` from `return val % 2 === 1;` to `return val % 2 !== 1;` so that the same tests would fail. And they do fail:

![](https://image.prntscr.com/image/Fp5KwyBrTxOLTMZV_wtCfQ.png)

Yet, BrowserStack would report all of them as completed:

![](https://image.prntscr.com/image/UrATdPA4R0SY2Y8_O0DXxg.png)

Which to me is no wonder since the logs for one of them show absolutely no requests apart from the start & take a screenshot ones:

![](https://image.prntscr.com/image/Mqgo-PJIQNmK_7fyNwUUkQ.png)

What am I missing here?

Keep in mind that I have not changed a single thing from the original sample apart from 1 byte to make the tests fail. So this couldn't be a configuration issue on my side, could it?

**Comment by TonyBogdanov** [comment]
Any plans on implementing this?

**Comment by sinstein** [comment]
Hi @TonyBogdanov 
I understand you have been trying to report test failure to BrowserStack so that your Automate dashboard reflects the result of your tests. Currently this feature is not provided as a part of runner but is available for use as [an API](https://www.browserstack.com/automate/rest-api#rest-api-sessions).

You can use the results of your tests and the API to mark your sessions as passed/failed and they will reflect on the dashboard. 

Please use the API as of now. We are looking at making this feature a part of the runner in a future release.

**Comment by TonyBogdanov** [comment]
Hi @sinstein 

Yes, that's exactly what customer support told me, but they also said they would put priority on the feature as it doesn't really make sense to have a test runner that can't report the results. That was 4 months ago, so I just wanted to know whether it is going to happen anytime soon.

Thanks anyway.

**Comment by mohitmun** [comment]
Closing this, Use BrowserStack API till we implement this feature
