### ISSUE TITLE
Cannot specify android 8 device

### ISSUE THREAD

**Issue by ddiukariev** [browserstack/browserstack-runner#196]
When I add to browsers config following entry:
	{
		"os": "android",
		"os_version": "8.0",
		"device": "Google Pixel"
	}
I get error: "Error from BrowserStack:  Error: Validation Failed - `os_version` invalid"
But according to https://www.browserstack.com/list-of-browsers-and-platforms?product=js_testing os version that I specified is valid.

**Comment by vedharish** [comment]
You also need to pass `realMobile` flag

```json
{
  "os": "android",
  "os_version": "8.0",
  "realMobile": true,
  "device": "Google Pixel"
}
```

**Comment by vedharish** [comment]
Closing as this was mostly because of the missing flag
