### ISSUE TITLE
Error: spawn ETXTBSY

### ISSUE THREAD

**Issue by dmedinag** [browserstack/browserstack-runner#209]
I'm getting this error when attempting to use the browserstack runner in my CI/CD pipeline:

```
Error: spawn ETXTBSY
    at ChildProcess.spawn (internal/child_process.js:357:11)
    at spawn (child_process.js:525:9)
    at execFile (child_process.js:216:15)
    at tunnelLauncher (/opt/crumbjs/node_modules/browserstack-runner/lib/local.js:23:22)
    at Timeout._onTimeout (/opt/crumbjs/node_modules/browserstack-runner/lib/local.js:191:11)
    at ontimeout (timers.js:424:11)
    at tryOnTimeout (timers.js:288:5)
    at listOnTimeout (timers.js:251:5)
    at Timer.processTimers (timers.js:211:10)
```

It looks like a similar [issue](https://github.com/browserstack/browserstack-local-nodejs/issues/19) was filed in other repo from Browserstack with the same error.

**Comment by Acconut** [comment]
I am struggling with the same problem where browserstack-runner is reporting an ETXTBSY error (see https://travis-ci.org/tus/tus-js-client/jobs/566880643#L321). Would it be possible to fix this?

**Comment by ckzgraphics** [comment]
@dmedinag - Could you provide some more details around the issue you are facing?

- What CI server are you using? (_eg- CircleCI, Jenkins, TravisCI, Azure, etc_)
- What are the parameters passed to the BrowserStackLocal binary when it is started?
- Are you facing this error while running a single test or while executing tests in parallel?

Also, can you **delete the old browserstack-runner package and try installing it again** ? 
`npm install browserstack-runner`

You may **also try to upgrade the package** - 
`npm upgrade browserstack-local `

**Comment by Acconut** [comment]
I can't tell for @dmedinag but we get the same error when running this script (https://github.com/tus/tus-js-client/blob/master/bin/browserstack-jasmine.js) on Travis CI. It basically just calls `browserstackRunner.run` and handles the callback. The version of browserstack-runner is 0.9.0. I hope that helps you a bit.

**Comment by dmedinag** [comment]
I'm afraid I can't replicate the issue anymore since the code generating it is from a previous position :/ I'm not working there anymore and don't have access to the code. Sorry guys

**Comment by Acconut** [comment]
The problem is solved for me by upgrading the `browserstack-runner` package and its dependencies. I also had to clean the build caches on Travis CI. Thank you very much for the help!

**Comment by twiss** [comment]
I'm still running into this issue with the latest `browserstack-runner` and cleared build caches on Travis CI: https://travis-ci.org/openpgpjs/openpgpjs/jobs/583375490#L279.

**Comment by Acconut** [comment]
The ETXTBSY problem resurfaced for me again and I opened a PR for a fix: https://github.com/browserstack/browserstack-runner/pull/217

@twiss You can try my solution by installing the fork using `npm install git://github.com/Acconut/browserstack-runner.git#fix_etxtbsy --save-dev`.
