### ISSUE TITLE
Retry Issue for Browserstack 

### ISSUE THREAD

**Issue by arpit28** [browserstack/browserstack-runner#211]
var Jasmine2HtmlReporter = require('protractor-jasmine2-html-reporter');
var browserstack = require('browserstack-local');
var webdriver = require('selenium-webdriver');
var JSONReporter = require('jasmine-bamboo-reporter');
var fs = require('fs');
var retry = require('protractor-retry').retry;
var NUMBER_OF_RETRIES = 2;
var shell = require('shelljs');

exports.config = {
    seleniumAddress: 'http://hub-cloud.browserstack.com/wd/hub',

    specs: ['./specs/backOffice/*.js'],

    //directConnect: true,

    // Below code is for Bamboo reports
    framework: 'jasmine2',
    beforeLaunch: function () {
        //clean up any residual/leftover from a previous run. Ensure we have clean
        //files for both locking and merging.
        if (fs.existsSync('jasmine-results.json.lock')) {
            fs.unlinkSync('jasmine-results.json.lock');
        }
        if (fs.existsSync('jasmine-results.json')) {
            fs.unlink('jasmine-results.json');
        }
    },

    'capabilities': {
        'browserstack.user': 'xxxxxxxx',
        'browserstack.key': 'xxxxxxx',
        'browserstack.local': true,
        'browserstack.debug': true,
        'os': 'OS X',
        'os_version': 'Sierra',
        'browserName': 'Chrome',
        'browser_version': '68.0',
        'resolution': '1280x960',
        'acceptSslCerts': true,
        'chromeOptions': {
            'args': ['incognito']
        }
    },

    // Code to start browserstack local before start of test
    beforeLaunch: function () {
        console.log("Connecting local");

        return new Promise(function (resolve, reject) {
            exports.bs_local = new browserstack.Local();
            exports.bs_local.start({'key': exports.config.capabilities['browserstack.key']}, function (error) {
                if (error) return reject(error);
                console.log('Connected. Now testing...');

                resolve();
            });
        });
    },

    // Code to stop browserstack local after end of test
    afterLaunch: function(){
          new Promise(function(resolve, reject){
             exports.bs_local.stop(resolve);
         });
    },

    afterLaunch: function () {

        return retry.afterLaunch(NUMBER_OF_RETRIES);
       
   },

    onCleanUp: function (results) {
        retry.onCleanUp(results);
    },

    onPrepare: function () {

        retry.onPrepare();
        browser.driver.manage().window().maximize();
        console.log("This is on prepare");
        global.EC = protractor.ExpectedConditions;
        global.d = require("./data/Data.js");

        //jasmine-bamboo-reporter -- >jasmine-results.json
        jasmine.getEnv().addReporter(new JSONReporter({
            file: 'jasmine-results.json', // by default it writes to jasmine.json
            beautify: true,
            indentationLevel: 4 // used if beautify === true
        }));

    },

    // Options to be passed to Jasmine-node.
    jasmineNodeOpts: {
        showColors: true, // Use colors in the command line report.

    }
};

Hi ^^^ is my conf.js file.
When I try to run it.
It looks for the failed specs abd before executing the rerun, I get get following error-
LocalError: Either another browserstack local client is running on your machine or some server is listening on port 45691
    at /Users/xxx/xxxx/xxx-xxx-functionals/node_modules/browserstack-local/lib/Local.js:58:20

I have tried various steps to avoid this issue infact tied to add
browser.driver.executeScript("kill $(lsof -t -i:45691)");
in the last spec but still no luck..
Looking for help

**Comment by arpit28** [comment]
LocalError: Either another browserstack local client is running on your machine or some server is listening on port 45691
    at /Users/xxxx/xxxx/xxx-xxx-functionals/node_modules/browserstack-local/lib/Local.js:58:20

**Comment by ray-pankaj** [comment]
You are trying to run selenium tests using browserstack-runner.
Duplicate of #186 
Closing. You can reopen the issue if you feel I have misunderstood the issue.

**Comment by arpit28** [comment]
@ray-pankaj 
1st Test runs fine.
Its only happening while re executing failing tests...(on second run)
Seems like Browserstack server is port is busy at the time of retry.

**Comment by ray-pankaj** [comment]
@arpit28 Somehow the previous local instance fails to stop. A workaround that is to use [local-identifier](https://www.browserstack.com/local-testing) which allows you to use multiple local instances.

**Comment by DeveloperChallenge** [comment]
Solved: LocalError: Either another browserstack local client is running on your machine or some server is listening on port 45691.

Same issue i was facing, finally, found the solution 
I had install web driver-namager and protractor separately. So, when you run test, you may run web driver-manager start and then run protractor. 

remember: 
**1. when you install protractor it will install webdriver-manager inside the protractor folder internally
2. When you start protractor, It will start and kill the webdriver-manager (selenium server)
3. you do not need to start web driver-manager differently. 
4. remover protractor from global and install it locally (inside project node_module)
nam install protractor --save-dev**

_package.json_ 
**"test": "cd e2e && protractorconf.js"**

Solved this issue

**Comment by alexoseland** [comment]
@DeveloperChallenge this didn't work for me...can you help me i think I must be doing something wrong. I installed webdriver-manager and protractor. But what is the command you are running next in your terminal to get BrowserStack to work?

**Comment by sauravkhdoolia** [comment]
I found out that this error was what it says: 

`kill $(lsof -i :45691)`

Something like that.

**Comment by aswinchembath** [comment]
> I found out that this error was what it says:
> 
> `kill $(lsof -i :45691)`
> 
> Something like that.

This worked for me

**Comment by DevFacts** [comment]
> @DeveloperChallenge this didn't work for me...can you help me i think I must be doing something wrong. I installed webdriver-manager and protractor. But what is the command you are running next in your terminal to get BrowserStack to work?

Fresh setup 
1. install protractor locally (within your project)
2. run command "webdriver-manager update"
3. in protractor config file, set, `directConnect=true` - Protractor will handle your selenium.

Note: 
1. No need to install webdriver separately
2. no need to pass selenium server url (selenium instance)
