### ISSUE TITLE
Is Browserstack dead?

### ISSUE THREAD

**Issue by DanielRuf** [browserstack/browserstack-runner#222]
There is a lack of communication and the current integration by you is broken.

https://github.com/browserstack/browserstack-runner/issues/221

Is Browserstack still actively supported?
This is quite problematic for us as we have to test against many different browser and OS combination for Foundation Sites.

**Comment by RohanImmanuel** [comment]
Hi @DanielRuf I have responded to the GitHub Issue [#221](https://github.com/browserstack/browserstack-runner/issues/221) rased by you.
